name: "Install Dependencies"

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: |
        npm install --force
        npm install -g @angular/cli
      shell: bash
