name: Undeploy All Stacks

on:
    workflow_dispatch:
        inputs:
            deploy_override:
                description: Set to YES to deploy (else run CI only).
            version:
                description: Provide a version in the format name_r.*.*.*.
env:
    REGION: us-east-1

jobs:
    setup:
        name: Setup variables
        runs-on: ubuntu-latest
        outputs:
            branch-name: ${{steps.get-branch-name.outputs.branch-name}}
        steps:
            - uses: actions/checkout@v2

            - name: Determine branch name
              uses: ./.github/actions/get-branch-name
              id: get-branch-name

    delete-web-stack:
        name: Delete web stack
        runs-on: ubuntu-latest
        needs: [setup]
        permissions:
            id-token: write
            contents: read
        env:
            PIPELINE_EXECUTION_ROLE: ${{ secrets.AWS_PIPELINE_EXEC_ROLE_ARN }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: aws-actions/setup-sam@v1

            - name: Assume the pipeline user role
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-region: ${{ env.REGION }}
                  role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
                  role-session-name: cicd-deleting
                  role-duration-seconds: 3600
                  role-skip-session-tagging: true

            - name: Delete web stack
              uses: ./.github/actions/delete-web-stack
              with:
                  branch-name: ${{needs.setup.outputs.branch-name}}
                  region: ${{env.REGION}}

    delete-client-api-stack:
        name: Delete client api stack
        runs-on: ubuntu-latest
        needs: [setup]
        permissions:
            id-token: write
            contents: read
        env:
            PIPELINE_EXECUTION_ROLE: ${{ secrets.AWS_PIPELINE_EXEC_ROLE_ARN }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: aws-actions/setup-sam@v1

            - name: Assume the pipeline user role
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-region: ${{ env.REGION }}
                  role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
                  role-session-name: cicd-deleting
                  role-duration-seconds: 3600
                  role-skip-session-tagging: true

            - name: Delete web stack
              uses: ./.github/actions/delete-api-stack
              with:
                  branch-name: ${{needs.setup.outputs.branch-name}}
                  region: ${{env.REGION}}
